config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :movies,   only: [:create]
  root                'static_pages#home'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :movies, dependent: :destroy
    attr_accessor   :remember_token
    before_save { self.email = email.downcase }
    validates :name,    presence: true,     length: { maximum: 50 } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }, allow_blank: true
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    def forget
        update_attribute(:remember_digest, nil)
    end
    
    def feed
        Movie.where("user_id = ?", id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    
    def create
        @movie = current_user.movies.build(movie_params)
        if @movie.save
          flash[:success] = "You added a movie to your list!"
          redirect_to '/'
        else
          @feed_items = []
          render '/'
        end
    end
    
    private
    
    def movie_params
        params.require(:movie).permit(:content)
    end
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   def home
    if logged_in?
      @movie  = current_user.movies.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
   end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    @movies = Movie.paginate(page: params[:page], per_page: 20)
  end
  def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Aww yisss, your account has been created!"
        redirect_to @user
      else
        render 'new'
      end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to 'home'
  end
    
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def current_user
        if (user_id = session[:user_id])
          @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
          user = User.find_by(id: user_id)
          if user && user.authenticated?(cookies[:remember_token])
            log_in user
            @current_user = user
          end
        end
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/movies/_movie.html.erb
<li id="movie-<%= movie.id %>">
  <span class="content"><%= movie.content %></span>
  <span class="rating"><%= movie.rating %></span>
  <span class="timestamp">
    posted <%= time_ago_in_words(movie.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if !object.nil? && object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="movies">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_movie_form.html.erb
<%= form_for (@movie) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div>
    <fieldset class="movie-form">
      <p>Movie Title</p>
      <input id="movie_content" name="movie[content]" type="text" class="field">
      <div style="padding-left:35px">
        <p>Rating</p>
        <input id="movie_rating" name="movie[rating]" type="number" max="5" min="0">
      </div>
	    <div style="padding-left:92px">
      	<input class="btn btn-primary" name="commit" type="submit" value="Add">
      </div>
    </fieldset>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h2 style="text-align:left"><%= current_user.name %></h2>
<span><%= link_to "view my profile", current_user %></span><br>

app/views/static_pages/help.html.erb
<h1>Help!!</h1>
<p>What is this website, where am I?</p>

app/views/static_pages/home.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="movies.css">
</head>

<div class="page_header">
<h1><%= link_to "Good Reels", "/" %></h1>
<p class="sub_header">Remember All the Movies You Watch!</p>
</div>
<% if logged_in? %>
        <aside class="col-md-4">
          <fieldset class="user_info">
            <%= render 'shared/user_info' %>
          </fieldset>
          <div style="position:relative; top: 10px; left:510px">
            <div class="top_buttons"><%= link_to "Log out |", logout_path, method: :delete %></div>
            <div class="top_buttons"><%= link_to "Settings |", edit_user_path(current_user) %></div>
            <div class="top_buttons"><%= link_to "Delete Account", current_user, method: :delete, data: { confirm: "You sure?" } %></div>
          </div>
          <section class="shared/movie_form">
            <%= render 'shared/movie_form' %>
          </section>
        </aside>
        <h3>Your Movies!</h3>
        <%= render 'shared/feed' %>
<%else%>
    <fieldset>
      <p style="display:block"><%= link_to "Let's get this party started!", signup_path %></p>
      <p style="display:block"><%= link_to "Already have an account?", login_path %></p>
    </fieldset>

<%end%>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1><%= link_to "Good Reels", "/" %></h1>
<h2>Update your profile</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1><%= link_to "Good Reels", "/" %></h1>
<h2>Sign up</h2>
<div class="h_line"></div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <fieldset>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <p>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      </p>
      <div class="submit">
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      </div>
    <% end %>
    </fieldset>
  </div>
</div>
<p class="small_text"> Already Have an Account? <%= link_to " Sign in here!", login_path%></p>
<p class = "tiny_text">© 2015 Shleew & Fuchs</p>

app/views/users/show.html.erb
<h1><%= link_to "Good Reels", "/" %></h1>
<h2 class="name"><%= @user.name %></h2>
<p class="email"><%= @user.email %></p>
<%= will_paginate @movies %>
<div>
    <% if logged_in? %>
        <% if @user.movies.any? %>
          <h3>Movies (<%= @user.movies.count %>)</h3>
          <ol class="movies">
            <%= render @movies %>
          </ol>
          <%= will_paginate @movies %>
        <% end %>
    <% end %>
</div>
<%= will_paginate @movies%>